# Generated by Django 5.0 on 2024-02-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='purpose',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
